"""add wiseword table

Revision ID: 82fbe2446ccb
Revises: 756b2f836ffd
Create Date: 2023-12-10 16:32:46.081223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fbe2446ccb'
down_revision: Union[str, None] = '756b2f836ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiseword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phrase')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiseword')
    # ### end Alembic commands ###
