"""add a task_id column to wiseword table

Revision ID: f1b9f15d5850
Revises: 82fbe2446ccb
Create Date: 2023-12-10 20:35:49.516830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b9f15d5850'
down_revision: Union[str, None] = '82fbe2446ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiseword', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wiseword', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wiseword', type_='foreignkey')
    op.drop_column('wiseword', 'task_id')
    # ### end Alembic commands ###
